name: go_router_lint_example
description: Go Router Lint Example

publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.0

dev_dependencies:
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  go_router_linter:
    path: ../
flutter:
  uses-material-design: true
