name: go_router_linter
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ^6.8.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.8

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
