name: go_router_linter
description: A custom linting package designed to enhance code quality and consistency when using the `go_router` package
version: 0.1.6

repository: https://github.com/AndrewDongminYoo/custom_linters

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ^6.11.0
  custom_lint_builder: ^0.7.0

dev_dependencies:
  test: ^1.25.14
  very_good_analysis: ^7.0.0
