name: custom_linters
description: Custom lint configuration files to use for Flutter development
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - packages/flutter_best_practices_lints/example
  - packages/flutter_best_practices_lints
  - packages/go_router_linter/example
  - packages/go_router_linter

dev_dependencies:
  melos: ^7.7.0
  test: ^1.31.1
  very_good_analysis: ^10.2.0

melos:
  scripts:
    generate:
      run: dart run melos exec --depends-on=build_runner -- "dart run build_runner build -d"
      description: Build all generated files for Dart & Flutter packages in this project.

    test:
      run: dart run melos exec --dir-exists=test --fail-fast -- "dart test --test-randomize-ordering-seed random"
      description: Run Dart VM tests for each package in this project.

    test:ci:
      run: dart run melos exec --dir-exists=test --fail-fast -- "dart test --test-randomize-ordering-seed random"
      description: Run Dart VM tests for each package in this project.

    format:
      run: dart run melos exec -- "dart fix --apply ; dart format ."
      description: Format all Dart files in this project.

    format:ci:
      run: dart run melos exec -- "dart format . --set-exit-if-changed"
      description: Check Dart file formatting for all packages in this project.

    analyze:
      run: dart run melos exec --concurrency=1 -- "dart analyze ."
      description: Analyze all Dart files in this project.
