name: go_router_linter
description: A custom lint rule that checks for the use of GoRouterHelper.
version: 0.1.2+1

repository: https://github.com/AndrewDongminYoo/custom_linters

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ^6.7.0
  custom_lint_builder: ^0.7.0

dev_dependencies:
  test: ^1.25.8
  very_good_analysis: ^6.0.0
