name: flutter_best_practices_lints
description: Lint rules that reflect best practices in Flutter development.
version: 0.2.0

repository: https://github.com/AndrewDongminYoo/custom_linters

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ">=4.6.0 <7.0.0"
  custom_lint_builder: ^0.7.0
  path: ^1.9.0

dev_dependencies:
  test: ^1.25.14
  very_good_analysis: ^7.0.0
