name: go_router_linter
description: A custom linting package designed to enhance code quality and consistency when using the `go_router` package
version: 0.1.9

repository: https://github.com/AndrewDongminYoo/custom_linters

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ^7.3.0
  custom_lint_builder: ^0.7.5

dev_dependencies:
  test: ^1.25.15
  very_good_analysis: ^7.0.0
